<?php

namespace FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OuvertureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvertureRepository extends EntityRepository
{
}
